services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: cea-server
    ports:
      - "8080:8080"
    environment:
      ENV: development
      # Database Configuration
      DB_DRIVER: org.postgresql.Driver
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USER: postgres
      DB_PASS: 1234567890abcdef
      # Redis Configuration
      REDIS_ENDPOINT: redis:6379
      # Email Configuration
      EMAIL_FROM_ADDR: noreply@example.com
      EMAIL_FROM_NAME: No Reply
      EMAIL_REPLY_TO_ADDR: info@example.com
      EMAIL_REPLY_TO_NAME: Support
      MAILER_SEND_TOKEN: abc
      # Firebase Admin
      GOOGLE_APPLICATION_CREDENTIALS: /service-account-file.json
      # CEA Configuration
      CEA_USERNAME: admin
      CEA_PASSWORD: password
    volumes:
      - keys:/keys
      - ./service-account-file.json:/service-account-file.json:ro
    networks:
      - internal
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    image: postgres:17-alpine
    container_name: cea-db
    # set shared memory limit when using docker compose
    shm_size: 128mb
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: 1234567890abcdef
    networks:
      - internal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
  redis:
    image: docker.io/library/redis:alpine
    container_name: cea-redis
    command: --save 60 1 --loglevel warning
    networks:
      - internal
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      timeout: 3s
    restart: unless-stopped
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
  keys:

networks:
  internal:
